// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSystem.Infrastructure.Models;

#nullable disable

namespace SchoolSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolSystemDbContext))]
    [Migration("20250424150559_EditGradIDToId")]
    partial class EditGradIDToId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolSystem.Domain.Models.ClassSubjects", b =>
                {
                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ClassID", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubjects", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Domain.Models.TeacherClass", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("TeacherClasses");
                });

            modelBuilder.Entity("SchoolSystem.Domain.Models.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubject", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69261C989728B2");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C0B2A11FBA");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClassroomId")
                        .HasName("PK__Classroo__11618EAA897F6DAF");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("grade")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Grade");

                    b.HasKey("Id")
                        .HasName("PK__Grades__54F87A570F8CF0B9");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52B997632E226");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A8BCF38FFE");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teachers__EDF25964673B85A0");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TimeSlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSlotId"));

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Timetable", b =>
                {
                    b.Property<int>("TimetableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TimetableID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimetableId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("ClassroomID");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int")
                        .HasColumnName("TimeSlotID");

                    b.HasKey("TimetableId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Timetable", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Domain.Models.ClassSubjects", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Class", "Class")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassID")
                        .IsRequired()
                        .HasConstraintName("FK_ClassSubjects_Classes");

                    b.HasOne("SchoolSystem.Infrastructure.Models.Subject", "subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassSubjects_Subjects");

                    b.Navigation("Class");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("SchoolSystem.Domain.Models.TeacherClass", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Class", "Class")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Infrastructure.Models.Teacher", "teacher")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("SchoolSystem.Domain.Models.TeacherSubject", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Infrastructure.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Attendance", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Attendance_Students");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Class", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Teacher", null)
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Grade", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Grades_Students");

                    b.HasOne("SchoolSystem.Infrastructure.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Grades_Subjects");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Student", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Students_Classes");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Timetable", b =>
                {
                    b.HasOne("SchoolSystem.Infrastructure.Models.Class", "Class")
                        .WithMany("Timetables")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Timetable_Classes");

                    b.HasOne("SchoolSystem.Infrastructure.Models.Classroom", "Classroom")
                        .WithMany("Timetables")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("FK_Timetable_Classrooms");

                    b.HasOne("SchoolSystem.Infrastructure.Models.Subject", "Subject")
                        .WithMany("Timetables")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Timetable_Subjects");

                    b.HasOne("SchoolSystem.Infrastructure.Models.TimeSlot", "TimeSlot")
                        .WithMany("Timetables")
                        .HasForeignKey("TimeSlotId")
                        .IsRequired()
                        .HasConstraintName("FK_Timetable_TimeSlots");

                    b.Navigation("Class");

                    b.Navigation("Classroom");

                    b.Navigation("Subject");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Class", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("Students");

                    b.Navigation("TeacherClasses");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Classroom", b =>
                {
                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("Grades");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("TeacherClasses");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SchoolSystem.Infrastructure.Models.TimeSlot", b =>
                {
                    b.Navigation("Timetables");
                });
#pragma warning restore 612, 618
        }
    }
}
